routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AppSettingsController;
use App\Http\Controllers\UrlController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\CountriesController;
use App\Http\Controllers\StatesController;
use App\Http\Controllers\CitiesController;
use App\Http\Controllers\ParametersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\OrdersController;

use App\Http\Controllers\TemplatesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class,'index']);
Route::get('/template/{id}',[HomeController::class,'detail']);
Route::get('/template/proses/{id}',[HomeController::class,'download']);
Route::get('/subscriptions',[HomeController::class,'listSubcriptions']);
Route::get('/subscriptions/check/{id}',[HomeController::class,'checkSubcriptions']);
Route::get('/subscriptions/payment/{id}',[HomeController::class,'payMidtrans']);

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
 
    return redirect('/app/beranda');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
 
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

Route::get('/forgot-password', function () {
    return view('auth.forgot-password');
})->middleware('guest')->name('forgot-password'); //--password.request

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::group(['prefix' => 'profile','as' => 'profile.'],function(){
        Route::get('/get-params/{id}',[ProfileController::class,'getParams']);

        Route::get('/',[ProfileController::class,'index'])->name('index');
        Route::post('/',[ProfileController::class,'updateProfile'])->name('update');
        Route::get('/account-information',[ProfileController::class,'indexAccountInformation'])->name('account-information');
        Route::post('/account-information',[ProfileController::class,'updateAccountInformation'])->name('account-information.update');
    });
    Route::group(['prefix' => 'app','as' => 'app.'],function(){
        

        Route::get('/signout',[AuthController::class,'signout'])->name('auth.logout');
            
        Route::get('/',[BerandaController::class,'index']);
        Route::get('/beranda',[BerandaController::class,'index'])->name('beranda');

        Route::match(['GET','POST'],'app-settings', [AppSettingsController::class,'index'])->name('app_setting');

        Route::resource('/url',UrlController::class);

        Route::resource('/permissions',PermissionsController::class);
        Route::get('permissions/generate/{id}', [PermissionsController::class,'generate']);

        Route::resource('/role',RoleController::class);

        Route::match(array('GET','POST'),'/role/configuration-permissions/{id}', [RoleController::class,'permission']);
        Route::match(array('GET','POST'),'/role/configuration-menus/{id}', [RoleController::class,'menu']);
        
        Route::resource('/users',UsersController::class);
        
        //----- Module Master -----//
        Route::resource('/countries',CountriesController::class);
        Route::resource('/states',StatesController::class);
        Route::get('get-states/{id}', [StatesController::class,'getStates']);

        Route::resource('/cities',CitiesController::class);
        Route::get('get-cities/{id}', [CitiesController::class,'getCities']);

        Route::resource('/parameters',ParametersController::class);

        Route::resource('/templates',TemplatesController::class);

        Route::resource('/customers',CustomersController::class);

        Route::resource('/orders',OrdersController::class);

        Route::resource('/invoice',InvoiceController::class);
        Route::group(['prefix' => 'invoice','as' => 'invoice.'],function(){
            Route::get('/pdf/{id}', [InvoiceController::class,'InvoicePDF'])->name('pdf');
            Route::post('/payment-update/{id}', [InvoiceController::class,'updatePayment'])->name('payment.update');
        });
        
        Route::get('/get-params/{id}',[BerandaController::class,'getParams']);
    });
});

app/Http/Controllers/CitiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Resources\DefaultCollection;
use App\Http\Requests\CitiesRequest;
use App\Models\User;
use App\Models\Cities;
use App\Models\States;
use App\Models\Countries;
use App\Providers\PermissionsProvider;
use Session, DB, Hash;

class CitiesController extends Controller
{
    public function __construct()
    {
        $this->title = "Cities";

        $this->middleware('permission:cities-view',['only' => 'index']);
        $this->middleware('permission:cities-create',['only' => ['create','store']]);
        $this->middleware('permission:cities-edit',['only' => ['edit']]);
        $this->middleware('permission:cities-update',['only' => 'update']);
        $this->middleware('permission:cities-delete',['only' => 'destroy']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $title = $this->title;
        if($request->ajax()){
            $data = Cities::with('createdByUser','updatedByUser','state')->get()->toArray();
            $kt = ktDatatable($data,$request->all());
            $request->meta = $kt;
            return response()->json(new DefaultCollection($data));
        }
        return view('cities.index', compact('title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $title = 'Create '.$this->title;
        $edit = false;
        $countries = Countries::orderBy('name','asc')
                                ->select('countries.*')
                                ->join('states','states.country_id','=','countries.id')
                                ->groupBy('Countries.id')
                                ->get();
        return view('cities.create',compact('edit','countries','title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CitiesRequest $request)
    {
        if($request->ajax()){
            DB::beginTransaction();
            try {
                Cities::create($request->all());
                DB::commit();
                return response()->json([
                    'status' => 'success',
                    'message' =>  ''
                ]);
            } catch (\Exception $e) {
                DB::rollback();
                return response()->json([
                    'status' => 'error',
                    'message' =>  $e->getMessage()
                ],500);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $title = 'Edit '.$this->title;
        $edit = true;
        $data = Cities::where('id',$id)->with('state')->firstOrFail();
        $countries = Countries::get();
        return view('cities.create',compact('edit','data','countries','title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CitiesRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            $url = Cities::find($id)->update($request->all());
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return response()->json([
                'status' => 'error',
                'message' =>  $e->getMessage()
            ],500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->ajax()){
            DB::beginTransaction();
            try {
                Cities::where('id',$id)->delete();
                DB::commit();

                $code = 200;
                $message = 'Delet '.$this->title.' Success!';
                $status = 'success';
                
                return response()->json([
                            'code'      => $code,
                            'message'   => $message
                        ]);

            } catch (\Exception $e) {
                DB::rollback();
                $code = 500;
                $message = 'Delet '.$this->title.' Failed!';
                return response()->json([
                            'code'      => $code,
                            'message'   => $message
                        ]);
            }
        }
    }

    public function getCities($id){
        $data = Cities::select('id','name')
                        ->where('state_id',$id)
                        ->get();
        return response()->json(['Data'=>$data]);
    }
}

resources/views/cities/create.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-md-12">
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                    <div class="card-toolbar">
                        <div class="example-tools justify-content-center">
                            <a href="{{ route('app.cities.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Back</a>
                        </div>
                    </div>
                </div>
                <form id="form">
                    <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                    @if($edit == true)
                    {{ method_field('PATCH') }}
                    @endif
                    @csrf
                    <div class="card-body">
                        <div class="validation-message"></div>
                        @include ('components.caution', ['title' => $title])
                        @include ('cities.form', ['formMode' => 'create'])
                    </div>
                    <div class="card-footer">
                        <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Change Data' : 'Add New' }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
            document.getElementById('form'),
            {
                fields: {
                    name: {
                        validators: {
                            notEmpty: {
                                message: 'Nama!'
                            },
                            stringLength: {
                                max:50,
                                message: 'Maximum is 50 characters.'
                            }
                        }
                    },
                    country_id: {
                        validators: {
                            notEmpty: {
                                message: 'Country!'
                            }
                        }
                    },
                    state_id: {
                        validators: {
                            notEmpty: {
                                message: 'State!'
                            }
                        }
                    },
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            var formData = $("#form").serialize();
            showLoading();
            $.post('{{ $edit == true ? route('app.cities.update',[app('request')->city])  : route('app.cities.store') }}', formData)
            .done(function(data){
                Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data cities!' : 'New Cities data added successfully!' }}", "success");
                hideLoading();
                window.location.href = "{{ route('app.cities.index') }}";
            }).fail(function(xhr,status,error){
                var errs = '<ul style="display:block">'
                if(xhr.status == 422){
                    p = xhr.responseJSON.errors;
                    for(var key in p){
                        p[key].forEach(err => {
                            errs += '<li><label class="error">'+err+'</label></li>'
                        })
                    }
                    errs += '</ul>';
                }else{
                    errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                }
                $('.validation-message').html(errs)
                hideLoading()
            });
        });
    });


    $("#country_id").change(function(){
        var val = $(this).val(), i;
        var y = document.getElementById('state_id');
        y.innerHTML = "<option>Please Wait... </option>";
        $.ajax({
            type: "GET",
            url : "{{url('app/get-states').'/'}}"+val,
            success: function(addr){
                y.innerHTML = "<option> </option>"
                for(i = 0; i < addr.Data.length; i++){
                    var option = document.createElement("option");
                    option.value = addr.Data[i].id;
                    option.text = addr.Data[i].name;
                    y.add(option);
                }
                return false;
            }
        });
    });
</script>
@endsection

resources/views/cities/form.blade.php
<div class="form-group">
    <label>Country<span class="text-danger">*</span></label>
    <select name="country_id" id="country_id" class="form-control" required>
        @if($edit == false)
        <option value="">-- Select Country --</option>
        @endif
        @foreach($countries as $ct)
        <option value="{{ $ct->id }}" {{ $edit == true ? ($data->country_id == $ct->id ? 'selected' : '') : '' }} {{ old('country_id') == $ct->id ? 'selected' : '' }}>{{ ucfirst($ct->name) }}</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label>State<span class="text-danger">*</span></label>
    <select name="state_id" id="state_id" class="form-control" required>
        @if($edit == true)
        <option value="{{ $data->state_id }}">{{ ucfirst($data->state->name) }}</option>
        @endif
    </select>
</div>
<div class="form-group">
    <label>Nama<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="name" placeholder="State Name" value="{{ isset($data->name) ? $data->name : old('name') }}">
</div>

resources/views/cities/index.blade.php
@extends('components.template')
@section('title',__($title))
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12 col-lg-12">
                <div class="card card-custom gutter-b example example-compact">
                {{kt_datatable('Data '.$title, Request::url())}}
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
<script>
var KTDatatableJsonRemoteDemo = function() {
    var dataTable = function() {
        var datatable = $('#kt_datatable').KTDatatable({
            data: {
                type: 'remote',
                source: {
                    read : {
                        method: 'GET',
                        url: '{{ route('app.cities.index') }}',
                    }
                },
                pageSize: 10,
            },
            layout: {
                scroll: false,
                footer: false
            },

            sortable: true,
            pagination: true,
            search: {
                input: $('#kt_datatable_search_query'),
                key: 'generalSearch'
            },
            columns: [
            {
                field: 'Actions',
                title: 'Actions',
                sortable: false,
                autoHide: false,
                width : 70,
                overflow: 'visible',
                template: function(data, type, full, meta) {
                        console.log(data);
                        return '\
                        <div class="d-flex align-items-center">\
                        </div>\
                        <div class="dropdown dropdown-inline">\
                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon mr-2" data-toggle="dropdown">\
                                <span class="svg-icon svg-icon-md">\
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">\
                                            <rect x="0" y="0" width="24" height="24"/>\
                                            <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>\
                                        </g>\
                                    </svg>\
                                </span>\
                            </a>\
                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">\
                                <ul class="navi flex-column navi-hover py-2">\
                                    <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">\
                                        Choose an action:\
                                    </li>\
                                    <li class="navi-item">\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'/edit" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-edit"></i></span>\
                                            <span class="navi-text">Edit</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'" class="navi-link btn-delete-on-table">\
                                            <span class="navi-icon"><i class="la la-trash"></i></span>\
                                            <span class="navi-text">Delete</span>\
                                        </a>\
                                    </li>\
                                </ul>\
                            </div>\
                        </div>\
                    ';
                },
            },
            {
                field: 'name',
                title: 'Nama',
            },
            {
                field: 'state_id',
                title: 'State',
                template: function(row) {
                    return row.state ? row.state.name : '-';
                },
            },
            {
                field: 'created_at',
                title: 'Created',
                template: function(row) {
                    return row.created_by_user ? row.created_by_user.name + '</br>' + Utils.dateIndonesia(row.created_at,true,true) : '-';
                },
            },
            {
                field: 'updated_at',
                title: 'Updated',
                template: function(row) {
                    return row.updated_by_user ? row.updated_by_user.name + '</br>' + Utils.dateIndonesia(row.updated_at,true,true) : '-';
                },
            }
            ],
        });
    };

    return {
        init: function() {
            dataTable();
        }
    };
}();

jQuery(document).ready(function() {
    KTDatatableJsonRemoteDemo.init();
});

</script>
<script src="{{ URL::asset('assets/js/KtDatatableDelete.js') }}"></script>
<script src="{{ URL::asset('assets/js/KtDatatableProses.js') }}"></script>
@endsection