routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AppSettingsController;
use App\Http\Controllers\UrlController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\CountriesController;
use App\Http\Controllers\StatesController;
use App\Http\Controllers\CitiesController;
use App\Http\Controllers\ParametersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\OrdersController;

use App\Http\Controllers\TemplatesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class,'index']);
Route::get('/template/{id}',[HomeController::class,'detail']);
Route::get('/template/proses/{id}',[HomeController::class,'download']);
Route::get('/subscriptions',[HomeController::class,'listSubcriptions']);
Route::get('/subscriptions/check/{id}',[HomeController::class,'checkSubcriptions']);
Route::get('/subscriptions/payment/{id}',[HomeController::class,'payMidtrans']);

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
 
    return redirect('/app/beranda');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
 
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

Route::get('/forgot-password', function () {
    return view('auth.forgot-password');
})->middleware('guest')->name('forgot-password'); //--password.request

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::group(['prefix' => 'profile','as' => 'profile.'],function(){
        Route::get('/get-params/{id}',[ProfileController::class,'getParams']);

        Route::get('/',[ProfileController::class,'index'])->name('index');
        Route::post('/',[ProfileController::class,'updateProfile'])->name('update');
        Route::get('/account-information',[ProfileController::class,'indexAccountInformation'])->name('account-information');
        Route::post('/account-information',[ProfileController::class,'updateAccountInformation'])->name('account-information.update');
    });
    Route::group(['prefix' => 'app','as' => 'app.'],function(){
        

        Route::get('/signout',[AuthController::class,'signout'])->name('auth.logout');
            
        Route::get('/',[BerandaController::class,'index']);
        Route::get('/beranda',[BerandaController::class,'index'])->name('beranda');

        Route::match(['GET','POST'],'app-settings', [AppSettingsController::class,'index'])->name('app_setting');

        Route::resource('/url',UrlController::class);

        Route::resource('/permissions',PermissionsController::class);
        Route::get('permissions/generate/{id}', [PermissionsController::class,'generate']);

        Route::resource('/role',RoleController::class);

        Route::match(array('GET','POST'),'/role/configuration-permissions/{id}', [RoleController::class,'permission']);
        Route::match(array('GET','POST'),'/role/configuration-menus/{id}', [RoleController::class,'menu']);
        
        Route::resource('/users',UsersController::class);
        
        //----- Module Master -----//
        Route::resource('/countries',CountriesController::class);
        Route::resource('/states',StatesController::class);
        Route::get('get-states/{id}', [StatesController::class,'getStates']);

        Route::resource('/cities',CitiesController::class);
        Route::get('get-cities/{id}', [CitiesController::class,'getCities']);

        Route::resource('/parameters',ParametersController::class);

        Route::resource('/templates',TemplatesController::class);

        Route::resource('/customers',CustomersController::class);

        Route::resource('/orders',OrdersController::class);

        Route::resource('/invoice',InvoiceController::class);
        Route::group(['prefix' => 'invoice','as' => 'invoice.'],function(){
            Route::get('/pdf/{id}', [InvoiceController::class,'InvoicePDF'])->name('pdf');
            Route::post('/payment-update/{id}', [InvoiceController::class,'updatePayment'])->name('payment.update');
        });
        
        Route::get('/get-params/{id}',[BerandaController::class,'getParams']);
    });
});

app/Models/Permissions.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;
use App\Traits\Uuid;

class Permissions extends Model
{
    use Uuid;
 
    protected $table = 'permissions';

    protected $primaryKey = 'id';
    
    protected $fillable = ['name','slug'];

    // disabled timestamps data
    public $timestamps = true;

    public $incrementing = false;

    // disable update col id
    protected $guarded = ['id'];
}

app/Http/Controllers/PermissionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PermissionsRequest;
use App\Http\Resources\PermimssionsCollection;
use App\Providers\PermissionsProvider;
use App\Models\Permissions;
use App\Models\Url;
use DB, Session;
class PermissionsController extends Controller
{
    public function __construct()
    {
        $this->title = "Permissions";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (PermissionsProvider::has($request, 'permissions-view')){
            $title = $this->title;
            if($request->ajax()){
                $permissions = Permissions::get()->toArray();
                $kt = ktDatatable($permissions,$request->all());
                $request->meta = $kt;
                return response()->json(new PermimssionsCollection($permissions));
            }
            return view('settings.permissions.index', compact('title'));
        }else{
            Session::flash('message', 'Anda tidak memiliki akses ke '.$this->title.'!'); 
            Session::flash('alert-class', 'alert-danger'); 
            return redirect('/app');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if (PermissionsProvider::has($request, 'permissions-create')){
            $title = $this->title;
            $edit = false;
            return view('settings.permissions.create',compact('edit','title'));
        }else{
            Session::flash('message', 'Anda tidak memiliki akses ke '.$this->title.'!'); 
            Session::flash('alert-class', 'alert-danger'); 
            return redirect('/app');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionsRequest $request)
    {
        if (PermissionsProvider::has($request, 'permissions-create')){
            if($request->ajax()){
                DB::beginTransaction();
                try {
                    Permissions::create($request->all());
                    DB::commit();
                    return response()->json([
                        'status' => 'success',
                        'message' =>  ''
                    ]);
                } catch (\Exception $e) {
                    DB::rollback();
                    return response()->json([
                        'status' => 'error',
                        'message' =>  $e->getMessage()
                    ],500);
                }
            }
        }else{
            Session::flash('message', 'Anda tidak memiliki akses ke '.$this->title.'!'); 
            Session::flash('alert-class', 'alert-danger'); 
            return redirect('/app');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if (PermissionsProvider::has($request, 'permissions-edit')){
            $title = $this->title;
            $edit = true;
            $permissions = Permissions::where('id',$id)->firstOrFail();
            return view('settings.permissions.edit',compact('edit','title','permissions'));
        }else{
            Session::flash('message', 'Anda tidak memiliki akses ke '.$this->title.'!'); 
            Session::flash('alert-class', 'alert-danger'); 
            return redirect('/app');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (PermissionsProvider::has($request, 'permissions-update')){
            DB::beginTransaction();
            try {
                $permissions = Permissions::find($id)
                                ->update($request->all());
                DB::commit();
            } catch (\Exception $e) {
                DB::rollback();
                return response()->json([
                    'status' => 'error',
                    'message' =>  $e->getMessage()
                ],500);
            }
        }else{
            Session::flash('message', 'Anda tidak memiliki akses ke '.$this->title.'!'); 
            Session::flash('alert-class', 'alert-danger'); 
            return redirect('/app');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if (PermissionsProvider::has($request, 'permissions-edit')){
            if($request->ajax()){
                DB::beginTransaction();
                try {
                    Permissions::where('id',$id)->delete();
                    DB::commit();

                    $code = 200;
                    $message = 'Delet '.$this->title.' Success!';
                    $status = 'success';
                    
                    return response()->json([
                                'code'      => $code,
                                'message'   => $message
                            ]);

                } catch (\Exception $e) {
                    DB::rollback();
                    $code = 500;
                    $message = 'Delet '.$this->title.' Failed!';
                    return response()->json([
                                'code'      => $code,
                                'message'   => $message
                            ]);
                }
            }
        }else{
            DB::rollback();
            $code = 402;
            $message = 'Delet '.$this->title.' Failed!';
            return response()->json([
                        'code'      => $code,
                        'message'   => $message
                    ]);
        }
    }

    public function generate(Request $request, $id) {
        if (PermissionsProvider::has($request, 'permissions-generate')){
            if($request->ajax()){
                DB::beginTransaction();
                try {
                    $url = Url::where('id',$id)->first();
                    DB::commit();
                    $permissions = array('create','edit','update','view','delete');

                    foreach($permissions as $val) {
                        permissions::create([
                            'name' => ucwords($url->name.' '.$val),
                            'slug' => $url->url.'-'.$val,
                        ]);
                    }

                    $code = 200;
                    $message = 'Proses '.$this->title.' Success!';
                    $status = 'success';
                    
                    return response()->json([
                                'code'      => $code,
                                'message'   => $message
                            ]);

                } catch (\Exception $e) {
                    DB::rollback();
                    $code = 500;
                    $message = 'Proses '.$this->title.' Failed!';
                    return response()->json([
                                'code'      => $code,
                                'message'   => $message
                            ]);
                }
            }
        }else{
            Session::flash('message', 'Anda tidak memiliki akses ke '.$this->title.'!'); 
            Session::flash('alert-class', 'alert-danger'); 
            return redirect('/app');
        }
    }
}

resources/views/settings/permissions/create.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="main d-flex flex-column flex-row-fluid">
    @include('components.breadcrumb')
    <div class="content flex-column-fluid" id="kt_content">
        <div class="row">
            <div class="col-md-12">
                <!--begin::Card-->
                <div class="card card-custom gutter-b example example-compact">
                    <div class="card-header">
                        <h3 class="card-title">{{$title}}</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <a href="{{ route('app.permissions.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                    <form id="form">
                        <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                        @csrf
                        <div class="card-body">
                            <div class="validation-message"></div>
                            @include ('components.caution', ['title' => $title])
                            @include ('settings.permissions.form', ['formMode' => 'create'])
                        </div>
                        <div class="card-footer">
                            <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah permissions' : 'Tambah Baru' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
			document.getElementById('form'),
			{
				fields: {
					nama: {
						validators: {
							notEmpty: {
								message: 'Nama permissions!'
							},
							stringLength: {
								max:50,
								message: 'Maximum is 50 characters.'
							}
						}
					},
                    slug: {
                        validators: {
                            notEmpty: {
                                message: 'Slug!'
                            },
                            stringLength: {
                                max:50,
                                message: 'Maximum is 50 characters.'
                            }
                        }
                    }
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            var formData = $("#form").serialize();
            showLoading();
            $.post('{{ $edit == true ? route('app.permissions.update',[app('request')->permissions])  : route('app.permissions.store') }}', formData)
            .done(function(data){
                Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data permissions!' : 'New Permissions data added successfully!' }}", "success");
                hideLoading();
                window.location.href = "{{ route('app.permissions.index') }}";
            }).fail(function(xhr,status,error){
                var errs = '<ul style="display:block">'
                if(xhr.status == 422){
                    p = xhr.responseJSON.errors;
                    for(var key in p){
                        p[key].forEach(err => {
                            errs += '<li><label class="error">'+err+'</label></li>'
                        })
                    }
                    errs += '</ul>';
                }else{
                    errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                }
                $('.validation-message').html(errs)
                hideLoading()
            });
        });
    });
</script>
@endsection

resources/views/settings/permissions/edit.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="main d-flex flex-column flex-row-fluid">
    @include('components.breadcrumb')
    <div class="content flex-column-fluid" id="kt_content">
        <div class="row">
            <div class="col-md-12">
                <!--begin::Card-->
                <div class="card card-custom gutter-b example example-compact">
                    <div class="card-header">
                        <h3 class="card-title">{{$title}}</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <a href="{{ route('app.permissions.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                    <form id="form">
                        <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                        {{ method_field('PATCH') }}
                        @csrf
                        <div class="card-body">
                            <div class="validation-message"></div>
                            @include ('components.caution', ['title' => $title])
                            @include ('settings.permissions.form', ['formMode' => 'create'])
                        </div>
                        <div class="card-footer">
                            <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah permissions' : 'Tambah Baru' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
			document.getElementById('form'),
			{
				fields: {
                    name: {
                        validators: {
                            notEmpty: {
                                message: 'Nama permissions!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maximum is 25 characters.'
                            }
                        }
                    },
                    slug: {
                        validators: {
                            notEmpty: {
                                message: 'Slug!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maximum is 25 characters.'
                            }
                        }
                    }
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            var formData = $("#form").serialize();
            showLoading();
            $.post('{{ $edit == true ? route('app.permissions.update',[app('request')->permission])  : route('app.permissions.store') }}', formData)
            .done(function(data){
                Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data permissions!' : 'New Permissions data added successfully!' }}", "success");
                hideLoading();
                window.location.href = "{{ route('app.permissions.index') }}";
            }).fail(function(xhr,status,error){
                var errs = '<ul style="display:block">'
                if(xhr.status == 422){
                    p = xhr.responseJSON.errors;
                    for(var key in p){
                        p[key].forEach(err => {
                            errs += '<li><label class="error">'+err+'</label></li>'
                        })
                    }
                    errs += '</ul>';
                }else{
                    errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                }
                $('.validation-message').html(errs)
                hideLoading()
            });
        });
    });
</script>
@endsection

resources/views/settings/permissions/form.blade.php
<div class="form-group">
    <label>Nama<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="name" id="name" value="{{ isset($permissions->name) ? $permissions->name : ''}}" required="true">
</div>
<div class="form-group">
    <label>Slug<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="slug" id="slug" value="{{ isset($permissions->slug) ? $permissions->slug : ''}}" required="true">
</div>

resources/views/settings/permissions/index.blade.php
@extends('components.template')
@section('title',__($title))
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12 col-lg-12">
                <div class="card card-custom gutter-b example example-compact">
                {{kt_datatable('Data '.$title, Request::url())}}
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
var KTDatatableJsonRemoteDemo = function() {
    var dataTable = function() {
        var datatable = $('#kt_datatable').KTDatatable({
            data: {
                type: 'remote',
                source: {
                    read : {
                        method: 'GET',
                        url: '{{ route('app.permissions.index') }}',
                    }
                },
                pageSize: 10,
            },
            layout: {
                scroll: false,
                footer: false
            },

            sortable: true,
            pagination: true,
            search: {
                input: $('#kt_datatable_search_query'),
                key: 'generalSearch'
            },
            columns: [
            {
                field: 'Actions',
                title: 'Actions',
                sortable: false,
                autoHide: false,
                overflow: 'visible',
                template: function(data, type, full, meta) {
                        return '\
                        <div class="d-flex align-items-center">\
                        </div>\
                        <div class="dropdown dropdown-inline">\
                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon mr-2" data-toggle="dropdown">\
                                <span class="svg-icon svg-icon-md">\
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">\
                                            <rect x="0" y="0" width="24" height="24"/>\
                                            <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>\
                                        </g>\
                                    </svg>\
                                </span>\
                            </a>\
                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">\
                                <ul class="navi flex-column navi-hover py-2">\
                                    <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">\
                                        Choose an action:\
                                    </li>\
                                    <li class="navi-item">\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'/edit" class="navi-link">\
                                            <i class="la la-edit"></i>\
                                            <span class="navi-text">Edit</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'" class="navi-link btn-delete-on-table" title="Delete">\
                                            <i class="la la-trash"></i>\
                                            <span class="navi-text">Delete</span>\
                                        </a>\
                                    </li>\
                                </ul>\
                            </div>\
                        </div>\
                    ';
                },
            },
            {
                field: 'name',
                title: 'Nama',
            },
            {
                field: 'slug',
                title: 'Slug',
            },
            {
                field: 'created_at',
                title: 'Created',
                template: function(row) {
                    return row.created_at ? Utils.dateIndonesia(row.created_at,true,true) : '-';
                },
            },
            {
                field: 'updated_at',
                title: 'Updated',
                template: function(row) {
                    return row.updated_at ? Utils.dateIndonesia(row.updated_at,true,true) : '-';
                },
            }
            ],
        });
    };

    return {
        init: function() {
            dataTable();
        }
    };
}();

jQuery(document).ready(function() {
    KTDatatableJsonRemoteDemo.init();
});

</script>
<script src="{{ URL::asset('assets/js/KtDatatableDelete.js') }}"></script>
@endsection