routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AppSettingsController;
use App\Http\Controllers\UrlController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\CountriesController;
use App\Http\Controllers\StatesController;
use App\Http\Controllers\CitiesController;
use App\Http\Controllers\ParametersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\OrdersController;

use App\Http\Controllers\TemplatesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class,'index']);
Route::get('/template/{id}',[HomeController::class,'detail']);
Route::get('/template/proses/{id}',[HomeController::class,'download']);
Route::get('/subscriptions',[HomeController::class,'listSubcriptions']);
Route::get('/subscriptions/check/{id}',[HomeController::class,'checkSubcriptions']);
Route::get('/subscriptions/payment/{id}',[HomeController::class,'payMidtrans']);

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
 
    return redirect('/app/beranda');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
 
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

Route::get('/forgot-password', function () {
    return view('auth.forgot-password');
})->middleware('guest')->name('forgot-password'); //--password.request

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::group(['prefix' => 'profile','as' => 'profile.'],function(){
        Route::get('/get-params/{id}',[ProfileController::class,'getParams']);

        Route::get('/',[ProfileController::class,'index'])->name('index');
        Route::post('/',[ProfileController::class,'updateProfile'])->name('update');
        Route::get('/account-information',[ProfileController::class,'indexAccountInformation'])->name('account-information');
        Route::post('/account-information',[ProfileController::class,'updateAccountInformation'])->name('account-information.update');
    });
    Route::group(['prefix' => 'app','as' => 'app.'],function(){
        

        Route::get('/signout',[AuthController::class,'signout'])->name('auth.logout');
            
        Route::get('/',[BerandaController::class,'index']);
        Route::get('/beranda',[BerandaController::class,'index'])->name('beranda');

        Route::match(['GET','POST'],'app-settings', [AppSettingsController::class,'index'])->name('app_setting');

        Route::resource('/url',UrlController::class);

        Route::resource('/permissions',PermissionsController::class);
        Route::get('permissions/generate/{id}', [PermissionsController::class,'generate']);

        Route::resource('/role',RoleController::class);

        Route::match(array('GET','POST'),'/role/configuration-permissions/{id}', [RoleController::class,'permission']);
        Route::match(array('GET','POST'),'/role/configuration-menus/{id}', [RoleController::class,'menu']);
        
        Route::resource('/users',UsersController::class);
        
        //----- Module Master -----//
        Route::resource('/countries',CountriesController::class);
        Route::resource('/states',StatesController::class);
        Route::get('get-states/{id}', [StatesController::class,'getStates']);

        Route::resource('/cities',CitiesController::class);
        Route::get('get-cities/{id}', [CitiesController::class,'getCities']);

        Route::resource('/parameters',ParametersController::class);

        Route::resource('/templates',TemplatesController::class);

        Route::resource('/customers',CustomersController::class);

        Route::resource('/orders',OrdersController::class);

        Route::resource('/invoice',InvoiceController::class);
        Route::group(['prefix' => 'invoice','as' => 'invoice.'],function(){
            Route::get('/pdf/{id}', [InvoiceController::class,'InvoicePDF'])->name('pdf');
            Route::post('/payment-update/{id}', [InvoiceController::class,'updatePayment'])->name('payment.update');
        });
        
        Route::get('/get-params/{id}',[BerandaController::class,'getParams']);
    });
});

resources/views/templates/create.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-md-12">
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                    <div class="card-toolbar">
                        <div class="example-tools justify-content-center">
                            <a href="{{ route('app.templates.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Back</a>
                        </div>
                    </div>
                </div>
                <form enctype="multipart/form-data" id="form">
                    <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                    @if($edit == true)
                    {{ method_field('PATCH') }}
                    @endif
                    @csrf
                    <div class="card-body">
                        <div class="validation-message"></div>
                        @include ('components.caution', ['title' => $title])
                        @include ('templates.form', ['formMode' => 'create'])
                    </div>
                    <div class="card-footer">
                        <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Change Data' : 'Add New' }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var vallang = 'Programming Language', i;
        var language = $("#language_id")[0];
        const selected = [];
        @if(isset($data))
        @foreach($data->language as $val)
        selected.push("{{$val->id}}");
        @endforeach
        @endif
        $.ajax({
            type: "GET",
            url : "{{url('app/get-params').'/'}}"+vallang,
            success: function(addr){
                language.innerHTML = "<option> </option>"
                for(i = 0; i < addr.Data.length; i++){
                    var option = document.createElement("option");
                    option.value = addr.Data[i].id;
                    if(jQuery.inArray(addr.Data[i].id, selected)) {
                        option.selected = true;
                    } else {
                        option.selected = false;
                    }
                    option.text = addr.Data[i].name;
                    language.add(option);
                }
                $('.selectpicker').selectpicker('refresh')
                return false;
            }
        });

        const fv = FormValidation.formValidation(
            document.getElementById('form'),
            {
                fields: {
                    name: {
                        validators: {
                            notEmpty: {
                                message: 'Nama!'
                            },
                            stringLength: {
                                max:100,
                                message: 'Maximum is 100 characters.'
                            }
                        }
                    },
                    slug: {
                        validators: {
                            notEmpty: {
                                message: 'Slug!'
                            },
                            stringLength: {
                                max:100,
                                message: 'Maximum is 100 characters.'
                            }
                        }
                    },
                    version: {
                        validators: {
                            notEmpty: {
                                message: 'Version!'
                            },
                            stringLength: {
                                max:100,
                                message: 'Maximum is 100 characters.'
                            }
                        }
                    },
                    desc: {
                        validators: {
                            callback: {
                                message: 'Description must be longer than 5 characters',
                                callback: function (value) {
                                    // Get the plain text without HTML
                                    const text = tinyMCE.activeEditor.getContent({
                                        format: 'text',
                                    });

                                    return text.length >= 5;
                                },
                            },
                        },
                    },
                    subscription_id: {
                        validators: {
                            notEmpty: {
                                message: 'Subscription!'
                            }
                        }
                    },
                    language_id: {
                        validators: {
                            notEmpty: {
                                message: 'Language!'
                            }
                        }
                    },
                    image: {
                        validators: {
                            notEmpty: {
                                message: 'Image!'
                            }
                        }
                    },
                    file: {
                        validators: {
                            notEmpty: {
                                message: 'File!'
                            },
                            file: {
                                extension: 'rar',
                                type: 'application/x-rar-compressed,application/zip',
                                message: 'Please choose a RAR / ZIP file',
                            },
                        }
                    },
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            $('#description').val(tinyMCE.activeEditor.getContent());
            var formData = $("#form").serialize();
            showLoading();
            $.ajax({
                url: "{{ $edit == true ? route('app.templates.update',[app('request')->template]) : route('app.templates.store') }}",
                type: "POST",
                dataType: "JSON",
                data: new FormData($('#form')[0]),
                processData: false,
                contentType: false,
                success: function (data)
                {
                    Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data templates!' : 'New templates data added successfully!' }}", "success");
                    hideLoading();
                    window.location.href = "{{ route('app.templates.index') }}";
                },
                error: function (xhr, status, error)
                {
                    var errs = '<ul style="display:block">'
                    if(xhr.status == 422){
                        p = xhr.responseJSON.errors;
                        for(var key in p){
                            p[key].forEach(err => {
                                errs += '<li><label class="error">'+err+'</label></li>'
                            })
                        }
                        errs += '</ul>';
                    }else{
                        errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                    }
                    $('.validation-message').html(errs)
                    hideLoading()
                }
            });
        });
        tinymce.init({
            selector: 'textarea',
            branding: false,
            menubar: false,
            setup: function (editor) {
                editor.on('keyup', function () {
                    fv.revalidateField('desc');
                });
            },
        });
    });

    $("#subscription_id").focus(function(){
        var val = 'Subscription', i;
        var y = $(this)[0];
        $.ajax({
            type: "GET",
            url : "{{url('app/get-params').'/'}}"+val,
            success: function(addr){
                y.innerHTML = "<option> </option>"
                for(i = 0; i < addr.Data.length; i++){
                    var option = document.createElement("option");
                    option.value = addr.Data[i].id;
                    option.text = addr.Data[i].name;
                    y.add(option);
                }
                return false;
            }
        });
    });
    var image1 = new KTImageInput('kt_image_1');
</script>
@endsection

resources/views/templates/form.blade.php
<div class="form-group">
    <label>Name<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="name" placeholder="Parameter Name" value="{{ isset($data->name) ? $data->name : old('name') }}">
</div>
<div class="form-group">
    <label>Slug<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="slug" placeholder="Slug" value="{{ isset($data->slug) ? $data->slug : old('slug') }}">
</div>
<div class="form-group">
    <label>Description<span class="text-danger">*</span></label>
    <textarea style="height: 200px" name="desc" class="input-reset ba b--black-20 pa2 mb2 db w-100">
        {{isset($data->desc) ? $data->desc : ''}}
    </textarea>
    <input type="hidden" name="description" id="description">
</div>
<div class="row">
    <div class="form-group col-md-6">
        <label>Version<span class="text-danger">*</span></label>
        <input type="text" class="form-control" name="version" placeholder="1.0.0" value="{{ isset($data->version) ? $data->version : old('version') }}">
    </div>
    <div class="form-group col-md-6">
        <label>Responsive</label>
        <label class="form-check">
            <input class="form-check-input" type="checkbox" name="responsive" value="true" {{isset($data->responsive) ? ($data->responsive == 1 ? 'checked' : '') : ''}}>
            <span class="form-check-label">
                Is this template responsive ?
            </span>
        </label>
    </div>
    <div class="form-group col-md-6">
        <label>Subcription<span class="text-danger">*</span></label>
        <select name="subscription_id" id="subscription_id" class="form-control" required>
            @if(isset($data))
            <option value="{{ $data->subscription_id }}">{{ ucfirst($data->subscription ? $data->subscription->name : '') }}</option>
            @endif
        </select>
    </div>

    <div class="form-group col-md-6">
        <label>Programming Language<span class="text-danger">*</span></label>
        <select name="language_id[]" id="language_id" class="selectpicker form-control" multiple required>
        </select>
    </div>
</div>
<div class="form-group row">
    <label>Image <span class="text-danger">*</span></label>
    <div class="col-lg-9 col-xl-6">
        <div class="image-input image-input-outline" id="kt_image_1">
            <div class="image-input-wrapper" style="background-image: url(//{{ isset($data) ? $data->path.'/'.$data->image : '' }})"></div>
            <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                <i class="fa fa-pen icon-sm text-muted"></i>
                <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                <input type="hidden" name="image_remove"/>
            </label>

            <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                <i class="ki ki-bold-close icon-xs text-muted"></i>
            </span>
        </div>
        <span class="form-text text-muted">Allowed file types:  png, jpg, jpeg.</span>
    </div>
</div>
<div class="form-group">
    <label>File (rar/zip) <span class="text-danger">*</span></label>
    <input type="file" class="form-control" name="file">
</div>  

resources/views/templates/index.blade.php
@extends('components.template')
@section('title',__($title))
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12 col-lg-12">
                <div class="card card-custom gutter-b example example-compact">
                {{kt_datatable('Data '.$title, Request::url())}}
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
<script>
var KTDatatableJsonRemoteDemo = function() {
    var dataTable = function() {
        var datatable = $('#kt_datatable').KTDatatable({
            data: {
                type: 'remote',
                source: {
                    read : {
                        method: 'GET',
                        url: '{{ route('app.templates.index') }}',
                    }
                },
                pageSize: 10,
            },
            layout: {
                scroll: false,
                footer: false
            },

            sortable: true,
            pagination: true,
            search: {
                input: $('#kt_datatable_search_query'),
                key: 'generalSearch'
            },
            columns: [
            {
                field: 'Actions',
                title: 'Actions',
                sortable: false,
                autoHide: false,
                width : 70,
                overflow: 'visible',
                template: function(data, type, full, meta) {
                        return '\
                        <div class="d-flex align-items-center">\
                        </div>\
                        <div class="dropdown dropdown-inline">\
                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon mr-2" data-toggle="dropdown">\
                                <span class="svg-icon svg-icon-md">\
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">\
                                            <rect x="0" y="0" width="24" height="24"/>\
                                            <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>\
                                        </g>\
                                    </svg>\
                                </span>\
                            </a>\
                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">\
                                <ul class="navi flex-column navi-hover py-2">\
                                    <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">\
                                        Choose an action:\
                                    </li>\
                                    <li class="navi-item">\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'/edit" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-edit"></i></span>\
                                            <span class="navi-text">Edit</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'" class="navi-link btn-delete-on-table">\
                                            <span class="navi-icon"><i class="la la-trash"></i></span>\
                                            <span class="navi-text">Delete</span>\
                                        </a>\
                                    </li>\
                                </ul>\
                            </div>\
                        </div>\
                    ';
                },
            },
            {
                field: 'name',
                title: 'Name',
            },
            {
                field: 'slug',
                title: 'Slug',
            },
            {
                field: 'version',
                title: 'Version',
            },
            {
                field: 'responsive',
                title: 'Responsive',
                template: function(row) {
                    return row.responsive == 1 ? 'True' : 'False';
                },
            },
            {
                field: 'subscription_id',
                title: 'Subscription',
                template: function(row) {
                    return row.subscription ? row.subscription.name + '</br>' + Utils.numberLabelFormat(row.subscription.value) : '-';
                },
            },
            {
                field: 'hit',
                title: 'Hit',
            },
            {
                field: 'language_id',
                title: 'Programing Language',
                template: function(row) {
                    const data = [];
                    $.each( row.language, function( key, value ) {
                        data.push(' '+value.name)
                    });
                    return data;
                },
            },
            {
                field: 'created_at',
                title: 'Created',
                template: function(row) {
                    return row.created_by_user ? row.created_by_user.name + '</br>' + Utils.dateIndonesia(row.created_at,true,true) : '-';
                },
            },
            {
                field: 'updated_at',
                title: 'Updated',
                template: function(row) {
                    return row.updated_by_user ? row.updated_by_user.name + '</br>' + Utils.dateIndonesia(row.updated_at,true,true) : '-';
                },
            }
            ],
        });
    };

    return {
        init: function() {
            dataTable();
        }
    };
}();

jQuery(document).ready(function() {
    KTDatatableJsonRemoteDemo.init();
});

</script>
<script src="{{ URL::asset('assets/js/KtDatatableDelete.js') }}"></script>
<script src="{{ URL::asset('assets/js/KtDatatableProses.js') }}"></script>
@endsection