routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AppSettingsController;
use App\Http\Controllers\UrlController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\CountriesController;
use App\Http\Controllers\StatesController;
use App\Http\Controllers\CitiesController;
use App\Http\Controllers\ParametersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\OrdersController;

use App\Http\Controllers\TemplatesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class,'index']);
Route::get('/template/{id}',[HomeController::class,'detail']);
Route::get('/template/proses/{id}',[HomeController::class,'download']);
Route::get('/subscriptions',[HomeController::class,'listSubcriptions']);
Route::get('/subscriptions/check/{id}',[HomeController::class,'checkSubcriptions']);
Route::get('/subscriptions/payment/{id}',[HomeController::class,'payMidtrans']);

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
 
    return redirect('/app/beranda');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
 
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

Route::get('/forgot-password', function () {
    return view('auth.forgot-password');
})->middleware('guest')->name('forgot-password'); //--password.request

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::group(['prefix' => 'profile','as' => 'profile.'],function(){
        Route::get('/get-params/{id}',[ProfileController::class,'getParams']);

        Route::get('/',[ProfileController::class,'index'])->name('index');
        Route::post('/',[ProfileController::class,'updateProfile'])->name('update');
        Route::get('/account-information',[ProfileController::class,'indexAccountInformation'])->name('account-information');
        Route::post('/account-information',[ProfileController::class,'updateAccountInformation'])->name('account-information.update');
    });
    Route::group(['prefix' => 'app','as' => 'app.'],function(){
        

        Route::get('/signout',[AuthController::class,'signout'])->name('auth.logout');
            
        Route::get('/',[BerandaController::class,'index']);
        Route::get('/beranda',[BerandaController::class,'index'])->name('beranda');

        Route::match(['GET','POST'],'app-settings', [AppSettingsController::class,'index'])->name('app_setting');

        Route::resource('/url',UrlController::class);

        Route::resource('/permissions',PermissionsController::class);
        Route::get('permissions/generate/{id}', [PermissionsController::class,'generate']);

        Route::resource('/role',RoleController::class);

        Route::match(array('GET','POST'),'/role/configuration-permissions/{id}', [RoleController::class,'permission']);
        Route::match(array('GET','POST'),'/role/configuration-menus/{id}', [RoleController::class,'menu']);
        
        Route::resource('/users',UsersController::class);
        
        //----- Module Master -----//
        Route::resource('/countries',CountriesController::class);
        Route::resource('/states',StatesController::class);
        Route::get('get-states/{id}', [StatesController::class,'getStates']);

        Route::resource('/cities',CitiesController::class);
        Route::get('get-cities/{id}', [CitiesController::class,'getCities']);

        Route::resource('/parameters',ParametersController::class);

        Route::resource('/templates',TemplatesController::class);

        Route::resource('/customers',CustomersController::class);

        Route::resource('/orders',OrdersController::class);

        Route::resource('/invoice',InvoiceController::class);
        Route::group(['prefix' => 'invoice','as' => 'invoice.'],function(){
            Route::get('/pdf/{id}', [InvoiceController::class,'InvoicePDF'])->name('pdf');
            Route::post('/payment-update/{id}', [InvoiceController::class,'updatePayment'])->name('payment.update');
        });
        
        Route::get('/get-params/{id}',[BerandaController::class,'getParams']);
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;
use App\Traits\Uuid;

class Role extends Model
{
    use Uuid;

    protected $table = 'role';

    protected $primaryKey = 'id';
    
    protected $fillable = ['name'];

    // disabled timestamps data
    public $timestamps = true;
    public $incrementing = false;

    // disable update col id
    protected $guarded = ['id'];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\RoleRequest;
use App\Http\Resources\RoleCollection;
use App\Models\Role;
use App\Models\Url;
use App\Models\UrlAccess;
use App\Models\Permissions;
use App\Models\RolePermissions;
use App\Providers\PermissionsProvider;
use Session, DB;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->title = "Roles";

        $this->middleware('permission:role-view',['only' => 'index']);
        $this->middleware('permission:role-edit',['only' => ['edit', 'destroy']]);
        $this->middleware('permission:role-update',['only' => 'update']);
        $this->middleware('permission:role-create',['only' => ['create','store']]);
        $this->middleware('permission:role-config',['only' => ['permission','menu']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $title = $this->title;
        if($request->ajax()){
            $role = Role::get()->toArray();
            $kt = ktDatatable($role,$request->all());
            $request->meta = $kt;
            return response()->json(new RoleCollection($role));
        }
        return view('settings.role.index', compact('title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $title = 'Tambah '.$this->title.' Baru';
        $edit = false;
        return view('settings.role.create',compact('edit','title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        if($request->ajax()){
            DB::beginTransaction();
            try {
                Role::create($request->all());
                DB::commit();
                return response()->json([
                    'status' => 'success',
                    'message' =>  ''
                ]);
            } catch (\Exception $e) {
                DB::rollback();
                return response()->json([
                    'status' => 'error',
                    'message' =>  $e->getMessage()
                ],500);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $title = 'Edit '.$this->title;
        $edit = true;
        $role = Role::where('id',$id)->firstOrFail();
        return view('settings.role.edit',compact('edit','role','title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $role = Role::find($id)->update($request->all());
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return response()->json([
                'status' => 'error',
                'message' =>  $e->getMessage()
            ],500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->ajax()){
            DB::beginTransaction();
            try {
                Role::where('id',$id)->delete();
                DB::commit();

                $code = 200;
                $message = 'Delet '.$this->title.' Success!';
                $status = 'success';
                
                return response()->json([
                            'code'      => $code,
                            'message'   => $message
                        ]);

            } catch (\Exception $e) {
                DB::rollback();
                $code = 500;
                $message = 'Delet '.$this->title.' Failed!';
                return response()->json([
                            'code'      => $code,
                            'message'   => $message
                        ]);
            }
        }
    }

    public function permission(Request $request, $id)
    {
        $title = 'Configuration Permissions '.$this->title;
        switch ($request->method()) {
            case 'GET':
                $config = Permissions::select('permissions.*','role_permissions.role_id','role_permissions.id as rp_id')
                            ->leftJoin('role_permissions', 'role_permissions.permission_id',DB::raw('permissions.id AND role_permissions.role_id = "' . $id.'"'))
                            ->orderBy('permissions.name','asc')
                            ->get();
                return view('settings.role.config.permission', compact('title','config'));
            break;

            case 'POST':
                DB::beginTransaction();
                try {
                    $data = $request->all();
                    $delete = RolePermissions::where('role_id', $id)->delete();
                    foreach ($data['akses'] as $key => $val) {
                        RolePermissions::create([
                            'permission_id' => $val,
                            'role_id' => $id,
                        ]);
                    }
                    DB::commit();
                    Session::flash('message', 'Add Permissions '.$this->title.' Success!'); 
                    Session::flash('alert-class', 'alert-success'); 
                    return redirect('app/role');
                } catch (\Exception $e) {
                    DB::rollback();
                    Session::flash('message', 'Add Permissions '.$this->title.' Failed!'); 
                    Session::flash('alert-class', 'alert-danger'); 
                    return redirect('app/role');
                }
            break;
        };
    }

    public function menu(Request $request, $id)
    {
        $title = 'Configuration Menus '.$this->title;
        switch ($request->method()) {
            case 'GET':
                $config = Url::select('url.*','url_access.role_id')->with('parent')
                        ->leftJoin('url_access', 'url_access.url_id',DB::raw('url.id AND url_access.role_id = "'.$id.'"'))
                        ->orderBy('position','asc')
                        ->orderBy('order','asc')
                        ->orderBy('parent_id','asc')
                        ->get();
                return view('settings.role.config.menu', compact('title','config'));
            break;

            case 'POST':
                DB::beginTransaction();
                try {
                    $data = $request->all();
                    $delete = UrlAccess::where('role_id', $id)->delete();
                    foreach ($data['akses'] as $key => $val) {
                        UrlAccess::create([
                            'url_id' => $val,
                            'role_id' => $id,
                        ]);
                    }
                    DB::commit();
                    Session::flash('message', 'Add Menus '.$this->title.' Success!'); 
                    Session::flash('alert-class', 'alert-success'); 
                    return redirect('app/role');
                } catch (\Exception $e) {
                    DB::rollback();
                    Session::flash('message', 'Add Menus '.$this->title.' Failed!'); 
                    Session::flash('alert-class', 'alert-danger'); 
                    return redirect('app/role');
                }
            break;
        };
    }
}

resources/views/settings/role/create.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-md-12">
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                    <div class="card-toolbar">
                        <div class="example-tools justify-content-center">
                            <a href="{{ route('app.role.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Kembali</a>
                        </div>
                    </div>
                </div>
                <form id="form">
                    <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                    @csrf
                    <div class="card-body">
                        <div class="validation-message"></div>
                        @include ('components.caution', ['title' => $title])
                        @include ('settings.role.form', ['formMode' => 'create'])
                    </div>
                    <div class="card-footer">
                        <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah role' : 'Tambah Baru' }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
            document.getElementById('form'),
            {
                fields: {
                    nama: {
                        validators: {
                            notEmpty: {
                                message: 'Nama role!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maximum is 25 characters.'
                            }
                        }
                    },
                    role: {
                        validators: {
                            notEmpty: {
                                message: 'role!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maximum is 25 characters.'
                            }
                        }
                    },
                    role: {
                        validators: {
                            stringLength: {
                                max:500,
                                message: 'Maximum is 500 characters.'
                            }
                        }
                    },
                    order: {
                        validators: {
                            intLength: {
                                max:11,
                                message: 'Maksimal adalah 11 angka/karakter.'
                            }
                        }
                    },
                    position: {
                        validators: {
                            notEmpty: {
                                message: 'Position!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maximum is 25 characters.'
                            }
                        }
                    }
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
            ).on('core.form.valid', function() {
                var formData = $("form").serialize();
                showLoading();
                $.post('{{ $edit == true ? route('app.role.update',[app('request')->role])  : route('app.role.store') }}', formData)
                .done(function(data){
                    Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data role!' : 'New Role data added successfully!' }}", "success");
                    hideLoading();
                    window.location.href = "{{ route('app.role.index') }}";
                }).fail(function(xhr,status,error){
                    var errs = '<ul style="display:block">'
                    if(xhr.status == 422){
                        p = xhr.responseJSON.errors;
                        for(var key in p){
                            p[key].forEach(err => {
                                errs += '<li><label class="error">'+err+'</label></li>'
                            })
                        }
                        errs += '</ul>';
                    }else{
                        errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                    }
                    $('.validation-message').html(errs)
                    hideLoading()
                });
            });
        });
    </script>
    @endsection

resources/views/settings/role/edit.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="main d-flex flex-column flex-row-fluid">
    @include('components.breadcrumb')
    <div class="content flex-column-fluid" id="kt_content">
        <div class="row">
            <div class="col-md-12">
                <!--begin::Card-->
                <div class="card card-custom gutter-b example example-compact">
                    <div class="card-header">
                        <h3 class="card-title">{{$title}}</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <a href="{{ route('app.role.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                    <form id="form">
                        <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                        {{ method_field('PATCH') }}
                        @csrf
                        <div class="card-body">
                            <div class="validation-message"></div>
                            @include ('components.caution', ['title' => $title])
                            @include ('settings.role.form', ['formMode' => 'create'])
                        </div>
                        <div class="card-footer">
                            <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah role' : 'Tambah Baru' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
			document.getElementById('form'),
			{
				fields: {
					parent_id: {
						validators: {
							stringLength: {
								max:36,
								message: 'Maximum is 36 characters.'
							}
						}
					},
					nama: {
						validators: {
							notEmpty: {
								message: 'Nama role!'
							},
							stringLength: {
								max:25,
								message: 'Maximum is 25 characters.'
							}
						}
					},
                    role: {
                        validators: {
                            notEmpty: {
                                message: 'role!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maximum is 25 characters.'
                            }
                        }
                    },
                    role: {
                        validators: {
                            stringLength: {
                                max:500,
                                message: 'Maximum is 500 characters.'
                            }
                        }
                    },
					order: {
						validators: {
							intLength: {
								max:11,
								message: 'Maximum is 11 characters.'
							}
						}
					},
					position: {
						validators: {
                            notEmpty: {
                                message: 'Position!'
                            },
							stringLength: {
								max:25,
								message: 'Maximum is 25 characters.'
							}
						}
					}
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            var formData = $("#form").serialize();
            showLoading();
            $.post('{{ $edit == true ? route('app.role.update',[app('request')->role])  : route('app.role.store') }}', formData)
            .done(function(data){
                Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data role!' : 'New Role data added successfully!' }}", "success");
                hideLoading();
                window.location.href = "{{ route('app.role.index') }}";
            }).fail(function(xhr,status,error){
                var errs = '<ul style="display:block">'
                if(xhr.status == 422){
                    p = xhr.responseJSON.errors;
                    for(var key in p){
                        p[key].forEach(err => {
                            errs += '<li><label class="error">'+err+'</label></li>'
                        })
                    }
                    errs += '</ul>';
                }else{
                    errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                }
                $('.validation-message').html(errs)
                hideLoading()
            });
        });
    });
</script>
@endsection

resources/views/settings/role/form.blade.php
<div class="form-group">
    <label>Nama<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="name" id="name" value="{{ isset($role->name) ? $role->name : ''}}" >
</div>

resources/views/settings/role/index.blade.php
@extends('components.template')
@section('title',__($title))
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12 col-lg-12">
                <div class="card card-custom gutter-b example example-compact">
                {{kt_datatable('Data '.$title, Request::url())}}
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
var KTDatatableJsonRemoteDemo = function() {
    var dataTable = function() {
        var datatable = $('#kt_datatable').KTDatatable({
            data: {
                type: 'remote',
                source: {
                    read : {
                        method: 'GET',
                        url: '{{ route('app.role.index') }}',
                    }
                },
                pageSize: 10,
            },
            layout: {
                scroll: false,
                footer: false
            },

            sortable: true,
            pagination: true,
            search: {
                input: $('#kt_datatable_search_query'),
                key: 'generalSearch'
            },
            columns: [
            {
                field: 'Actions',
                title: 'Actions',
                sortable: false,
                autoHide: false,
                overflow: 'visible',
                template: function(data, type, full, meta) {
                        return '\
                        <div class="dropdown dropdown-inline">\
                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon mr-2" data-toggle="dropdown">\
                                <span class="svg-icon svg-icon-md">\
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">\
                                            <rect x="0" y="0" width="24" height="24"/>\
                                            <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>\
                                        </g>\
                                    </svg>\
                                </span>\
                            </a>\
                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">\
                                <ul class="navi flex-column navi-hover py-2">\
                                    <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">\
                                        Choose an action:\
                                    </li>\
                                    <li class="navi-item">\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'/edit" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-edit"></i></span>\
                                            <span class="navi-text">Edit</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/configuration-permissions/")}}'+data.id+'" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-cog"></i></span>\
                                            <span class="navi-text">Configuration Permissions</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/configuration-menus/")}}'+data.id+'" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-cog"></i></span>\
                                            <span class="navi-text">Configuration Menus</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'" class="navi-link btn-delete-on-table">\
                                            <span class="navi-icon"><i class="la la-trash"></i></span>\
                                            <span class="navi-text">Delete</span>\
                                        </a>\
                                    </li>\
                                </ul>\
                            </div>\
                        </div>\
                    ';
                },
            },
            {
                field: 'name',
                title: 'Nama',
            },
            {
                field: 'created_at',
                title: 'Created',
                template: function(row) {
                    return row.created_at ? Utils.dateIndonesia(row.created_at,true,true) : '-';
                },
            },
            {
                field: 'updated_at',
                title: 'Updated',
                template: function(row) {
                    return row.updated_at ? Utils.dateIndonesia(row.updated_at,true,true) : '-';
                },
            }
            ],
        });
    };

    return {
        init: function() {
            dataTable();
        }
    };
}();

jQuery(document).ready(function() {
    KTDatatableJsonRemoteDemo.init();
});

</script>
<script src="{{ URL::asset('assets/js/KtDatatableDelete.js') }}"></script>
<script src="{{ URL::asset('assets/js/KtDatatableProses.js') }}"></script>
@endsection